language: r
sudo: false
cache: packages

warnings_are_errors: false

matrix:
  include:
    - name: release
      r: release
      r_check_args: --as-cran --no-build-vignettes --ignore-vignettes
    - name: devel
      r: devel
      r_check_args: --as-cran --no-build-vignettes --use-valgrind --ignore-vignettes
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      addons:
        apt:
          packages:
            - valgrind
      script:
        - R CMD build --no-resave-data --no-build-vignettes .
        - travis_wait R CMD check "${PKG_TARBALL}" --as-cran --no-build-vignettes --ignore-vignettes --use-valgrind; CHECK_RET=$?

r_check_args: --as-cran --no-build-vignettes --ignore-vignettes

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
